### PR TITLE
Harmonize returned messages

### PR DESCRIPTION
**Pull request by breml**
Always end the returned messages in the JSON response with a full stop.

### CODE REVIEW

**Comment by floragunncom** [comment]
Merged here https://github.com/floragunncom/search-guard-enterprise-modules/commit/dabed9b89db68cbe894cdfdc6166c387504b0c77

**Comment by floragunncom** [comment]
Thx for contributing

**Comment by breml** [comment]
@floragunncom I was not aware, that I need to perform this change in the `search-guard-enterprise-modules` repo. Currently the structure of the repos (as well as in some cases the usage of the branches) is a little bit unclear. Do you somewhere have a reference for external contributors?

**Comment by floragunncom** [comment]
for everything which is ES/SG 5.x related the separate repos are relevant, everything ES/SG 6 related it's the search-guard-enterprise-modules repo

**Pull request closed without merging**
